AllCops:
  Include:
    - Gemfile
    - Guardfile
    - Rakefile
    - barge.gemspec
  Exclude:
    - 'bin/**/*'
    - 'spec/dummy/**/*'
    - 'scorm_rte.gemspec'

Documentation:
  Enabled: false

Encoding:
  Enabled: false
